spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.open-in-view=false

spring.liquibase.enabled=true
spring.thymeleaf.check-template-location=false

server.servlet.context-path=/api

jwt.expiration=3600000
jwt.secret=${JWT_SECRET}
spring.datasource.url=${MYSQLDB_URL}
spring.datasource.username=${MYSQLDB_USER}
spring.datasource.password=${MYSQLDB_ROOT_PASSWORD}
server.port=${SPRING_DOCKER_PORT}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Load .env file
spring.config.import=optional:file:.env[.properties]
